#ifndef DISPLAY_ST7735_H_
#define DISPLAY_ST7735_H_

#include "driver/spi_master.h"

// M5stickC
#define TTGO_T_WRISTBAND_WIDTH 160
#define TTGO_T_WRISTBAND_HEIGHT 80
#define TTGO_T_WRISTBAND_MOSI_GPIO 19
#define TTGO_T_WRISTBAND_SCLK_GPIO 18
#define TTGO_T_WRISTBAND_CS_GPIO 5
#define TTGO_T_WRISTBAND_DC_GPIO 23
#define TTGO_T_WRISTBAND_RESET_GPIO 26
#define TTGO_T_WRISTBAND__BL_GPIO 27

#define TTGO_T_WRISTBAND_OFFSETX 1
#define TTGO_T_WRISTBAND_OFFSETY 26

#define TTGO_T_WRISTBAND_INTERFACE_OFFSETX 16
#define TTGO_T_WRISTBAND_INTERFACE_OFFSETY 8

#define TTGO_T_WRISTBAND_LANDSCAPE_FLIPPED 0x68
#define TTGO_T_WRISTBAND_LANDSCAPE 0xA8

#define SPI_COMMAND_MODE 0
#define SPI_DATA_MODE 1

#endif
